### ISSUE TITLE
Mock-Up

### ISSUE THREAD

**Issue by sophimkep** [PNC-WEP-ONE-WEEK-PROJECT/PHP-DB-G9#1]
design mock up

**Comment by VichetMorm** [comment]
![Contact page](https://user-images.githubusercontent.com/90229555/158559210-10edc555-696c-4b98-9a7e-59227e98ce7a.png)
![display comment](https://user-images.githubusercontent.com/90229555/158559217-d5837e66-46cc-4231-8e02-d1bdcc20ccd1.png)
![edit contact](https://user-images.githubusercontent.com/90229555/158559222-bac998ce-470a-4469-bf81-770c843d364d.png)
![edit post](https://user-images.githubusercontent.com/90229555/158559225-49d7d49f-a251-4263-9837-9a515f3e7544.png)
![Home page](https://user-images.githubusercontent.com/90229555/158559227-ee255816-5120-4e78-bc77-d5cab5964b07.png)
![write comment](https://user-images.githubusercontent.com/90229555/158559236-89a4fba5-3ef3-4c4c-a273-35e4dc47a16b.png)
![add post](https://user-images.githubusercontent.com/90229555/158559238-11603f80-9ae6-45f1-8eb3-fd108c1ad715.png)
